In [ ]:
import numpy as np
x = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0,1,1,1])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [ ]:
y

array([0, 1, 1, 1])

In [ ]:
w = np.array([1,1])
w

array([1, 1])

In [ ]:
b = -0.5

In [ ]:
pred = []
for a in x:
  y_hat = np.dot(a,w)+b
  pred.append(activation(y_hat))

In [ ]:
pred

[0, 1, 1, 1]

In [ ]:
def activation(z):
  if z >= 0:
    return 1
  else:
    return 0


In [ ]:
import math
import numpy as np

In [ ]:
epochs = 100
alpha = 0.2

In [ ]:
w0 = np.random.random()
w1 = np.random.random()
w2 = np.random.random()
print(f'Initial weights:')
print(f'w0 = {w0}, w1 = {w1}, w2 = {w2}')


Initial weights:
w0 = 0.4973729625229759, w1 = 0.15992102172842115, w2 = 0.30945922200148057


In [ ]:
del_w0 = 1
del_w2 = 1
del_w1 = 1

In [ ]:
train_data_temp = [[0,0,0], [0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,1,0],[1,0,1],[1,1,1]]
train_data = np.asarray(train_data_temp)
op = np.array([0,1,1,1,1,1,1,1])

In [ ]:
op

array([0, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
train_data

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [1, 1, 1]])

y = (x*w)+b

In [ ]:
bias = 0
for i in range(epochs):
  j = 0
  for x in train_data:
    y_hat = w0*x[0] + w1*x[1] + w2*x[2] + bias

    if(y_hat >= 0):
      act = 1
    else:
      act = 0

    err = op[j] - act

    del_w0 = alpha*x[0]*err
    del_w1 = alpha*x[1]*err
    del_w2 = alpha*x[2]*err

    w0 = w0 + del_w0
    w1 = w1 + del_w1
    w2 = w2 + del_w2

    j=j+1

    print('epochs', i+1, 'error:', err)
    print(del_w0, del_w1, del_w2)

print('final weights:')
print('w0 =', w0, 'w1 = ', w1, 'w2 = ', w2)



epochs 1 error: -1
-0.0 -0.0 -0.0
epochs 1 error: 0
0.0 0.0 0.0
epochs 1 error: 0
0.0 0.0 0.0
epochs 1 error: 0
0.0 0.0 0.0
epochs 1 error: 0
0.0 0.0 0.0
epochs 1 error: 0
0.0 0.0 0.0
epochs 1 error: 0
0.0 0.0 0.0
epochs 1 error: 0
0.0 0.0 0.0
epochs 2 error: -1
-0.0 -0.0 -0.0
epochs 2 error: 0
0.0 0.0 0.0
epochs 2 error: 0
0.0 0.0 0.0
epochs 2 error: 0
0.0 0.0 0.0
epochs 2 error: 0
0.0 0.0 0.0
epochs 2 error: 0
0.0 0.0 0.0
epochs 2 error: 0
0.0 0.0 0.0
epochs 2 error: 0
0.0 0.0 0.0
epochs 3 error: -1
-0.0 -0.0 -0.0
epochs 3 error: 0
0.0 0.0 0.0
epochs 3 error: 0
0.0 0.0 0.0
epochs 3 error: 0
0.0 0.0 0.0
epochs 3 error: 0
0.0 0.0 0.0
epochs 3 error: 0
0.0 0.0 0.0
epochs 3 error: 0
0.0 0.0 0.0
epochs 3 error: 0
0.0 0.0 0.0
epochs 4 error: -1
-0.0 -0.0 -0.0
epochs 4 error: 0
0.0 0.0 0.0
epochs 4 error: 0
0.0 0.0 0.0
epochs 4 error: 0
0.0 0.0 0.0
epochs 4 error: 0
0.0 0.0 0.0
epochs 4 error: 0
0.0 0.0 0.0
epochs 4 error: 0
0.0 0.0 0.0
epochs 4 error: 0
0.0 0.0 0.0
epochs 5 error: -1
-0.0 